name: flutter_libepiccash
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  code_assets: ^1.2.1
  flutter:
    sdk: flutter
  ffi: ^2.2.0
  hooks: ^2.1.0
  native_toolchain_rust: ^1.0.6
  decimal: ^2.1.0
  mutex: ^3.0.0
  uuid: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^21.0.0
  flutter_lints: ^6.0.0
